---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ nginx_metrics_service_name }}'
    consul_services:
      - name: '{{ nginx_metrics_service_name }}'
        tags: ['ipfs', 'cluster']
        port: '{{ nginx_metrics_listen_port }}'
        address: '{{ ansible_local.tinc.vpn_ip }}'
        checks:
          - id: '{{ nginx_metrics_service_name }}-status'
            name: Nginx Metrics Healthcheck
            type: http
            http: 'http://localhost:{{ nginx_metrics_listen_port }}/'
