---
- name: 'Template status config: {{ nginx_metrics_service_name }}'
  template:
    src: nginx-metrics.conf.j2
    dest: '{{ nginx_metrics_nginx_path }}/sites-available/{{ nginx_metrics_service_name }}.conf'
  notify: reload nginx

- name: 'Symlink status config: {{ nginx_metrics_service_name }}'
  file:
    src: '{{ nginx_metrics_nginx_path }}/sites-available/{{ nginx_metrics_service_name }}.conf'
    dest: '{{ nginx_metrics_nginx_path }}/sites-enabled/{{ nginx_metrics_service_name }}.conf'
    state: link

- name: Reload nginx
  service:
    name: 'nginx'
    state: 'reloaded'
